# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present

      - name: Run Tests
        id: tests
        run: npm run test-regression-chrome

      - name: Print Test Result
        run: echo ${{ steps.tests.outcome }}

      - name: Always Upload Artifacts
        if: always() # This step will run regardless of previous step outcomes
        run: |
          echo "Uploading Artifacts"
          mkdir -p ./output # Create the output directory if it doesn't exist
          # Copy the files you want to upload to the output directory
          cp -r ./path/to/files ./output

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./output

      - name: Print Working Directory
        run: pwd
