# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  setup:
    name: Set up Node.js and Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x  # Use a specific Node.js version for setup
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Build
        run: npm run build --if-present

  lint:
    name: Run Linters
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Use Node.js 18.x for linting
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  tests:
    name: Run Tests
    needs: [build, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} for testing
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Run Tests
        run: npm run test-regression-chrome

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./output
