# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present

      - name: Run Tests
        id: tests
        run: npm run test-regression-chrome || echo "Tests failed"

      - name: Print Test Result
        run: echo ${{ steps.tests.outcome }}

  upload-artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output

  set-workflow-status:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Set Workflow Status
        run: echo "Tests failed" && exit 1
